config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'buildings#index'
  post '/buildings/guest_sign_in', to: 'buildings#new_guest'

  resources :home
  resources :boards do
    collection do
      get 'search'
    end
    resources :comments, only: :create
    resources :likes, only: %i[post create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, foreign_key: :board_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  geocoded_by :address
  after_validation :geocode

  def self.search(search)
    if search != ""
      Board.where('title LIKE(?) OR municipality LIKE(?) OR building_name LIKE(?)', "%#{search}%","%#{search}%","%#{search}%")
    else
      Board.all
    end
  end

  with_options presence: true do
    validates :title, presence: { message: '：タイトルを入力してください。' }, length: { maximum: 40 }
    validates :prefecture_id, numericality: { other_than: 0, message: '：都道府県を選択してください' }
    validates :municipality, presence: { message: '：市区町村を入力してください。' }
    validates :question_or_impressions, presence: { message: '：「質問内容」もしくは「住んでみての感想」のいずれかは必須です。' }
  end

  validates :question, length: { maximum: 1000 }
  validates :impressions, length: { maximum: 1000 }

  def address
    [prefecture.name, municipality, edaban].compact.join
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

private

def question_or_impressions
  question.presence || impressions.presence
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :text, presence: { message: 'を入力してください。' }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates_uniqueness_of :board_id, scope: :user_id
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '選択してください' },
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }, { id: 48, name: '未定' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname, uniqueness: { case_sensitive: true }
    validates :email, uniqueness: { case_sensitive: true }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, length: { minimum: 8 }
  end

  has_many :boards
  has_many :comments
  has_many :likes
  has_many :like_boards, through: :likes, source: :board

  def already_liked?(board)
    likes.exists?(board_id: board.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(_resource)
    home_index_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.includes(:user)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to home_index_path
    else
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
    gon.board = @board
    @comment = Comment.new
    @comments = @board.comments.order('created_at ASC')
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board.id)
    else
      render :edit
    end
  end

  def destroy
    @board = Board.find(params[:id])
    if current_user.id == @board.user.id
      @board.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    @boards = Board.search(params[:search])
  end

  private

  def board_params
    params.require(:board).permit(:title, :prefecture_id, :municipality, :edaban, :building_name, :question,
                                  :impressions, :image).merge(user_id: current_user.id)
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @boards = Board.includes(:user)
    if user_signed_in?
      render 'home/index'
    else
      render 'buildings/index'
    end
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.alphanumeric(8)
      # 大文字、小文字のアルファベット、数字からランダムに８桁のパスワードを生成
      user.nickname = 'ゲスト'
    end
    sign_in user
    redirect_to home_index_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to board_path(params[:board_id])
    else
      # render template: 'boards/show'
      flash[:error_messages] = @comment.errors.full_messages
      redirect_to board_path(params[:board_id])
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :board_id).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.includes(:like).where(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_like

  def create
    @like = current_user.likes.create(board_id: params[:board_id])
    redirect_to board_path(params[:board_id])
  end

  def destroy
    @like = current_user.likes.find_by(board_id: @board.id)
    @like.destroy
    redirect_to board_path(params[:board_id])
  end

  private

  def set_like
    @board = Board.find(params[:board_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/boards/edit.html.erb
<%= render partial: "layouts/nav"%>
<div class="main-box">
  <div class="header-box">
    <h1 class="header-text header-border">編集する</h1>
  </div>

<%= render partial: "layouts/form"%>
 

app/views/boards/index.html.erb
<%= render partial: "layouts/nav"%>
<%= render partial: "layouts/board_index"%>
<%= render partial: "layouts/footer"%>

app/views/boards/new.html.erb
<%= render partial: "layouts/nav"%>
<div class="main-box">
  <div class="header-box">
    <h1 class="header-text header-border">掲示板を新規作成</h1>
  </div>
  <div class="form-box">

    <%= form_with model: @board, local: true do |f| %>
    
    <div class="form-group">
      <label for="exampleInputEmail1">タイトル</label>
      <span class="badge badge-pill badge-danger">必須</span>
        <%= f.text_field :title, class:"form-control", id:"title" %>
    </div>
    <div class="form-group">
      <label for="exampleFormControlSelect1">都道府県</label>
      <span class="badge badge-pill badge-danger">必須</span>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name,{prompt: false}, {class:"form-control",id:"exampleFormControlSelect1"}) %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">市区町村</label>
      <span class="badge badge-pill badge-danger">必須</span>
        <%= f.text_field :municipality, class:"form-control", id:"municipality", placeholder:"〇〇市〇〇町"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">番地</label>
      <span class="badge badge-pill badge-secondary">任意</span>
        <%= f.text_field :address, class:"form-control", id:"address", placeholder:"〇丁目〇番地"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">建物名・マンション名</label>
      <span class="badge badge-pill badge-secondary">任意</span>
        <%= f.text_field :building_name, class:"form-control", id:"building_name"%>
    </div>
    <div class="form-group">
      <label for="exampleFormControlFile1">外観写真</label>
      <span class="badge badge-pill badge-secondary">任意</span>
        <%= f.file_field :image, class:"form-control-file", id:"item-image" %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">質問内容</label>
      <%= f.text_area :question, class:"form-control", id:"question"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">良い点</label>
      <%= f.text_area :good_points, class:"form-control", id:"good_points"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">改善してほしい点</label>
      <%= f.text_area :bad_points, class:"form-control", id:"bad_points"%>
    </div>
      <%= f.submit "掲示板作成",class:"btn btn-primary" %>
    </div>

    <% end %>
    
  </div>
</div>

app/views/boards/search.html.erb
<%= render partial: "layouts/nav"%>
<%= render partial: "layouts/board_index"%>
<%= render partial: "layouts/footer"%>

app/views/boards/show.html.erb
<%= render partial: "layouts/nav"%>
<div class="main-box">
  <div class="header-box">
    <h1 class="header-text header-border">掲示板詳細</h1>
  </div>

  <div class="form-box">
    <div class="show-btn-box">
      <%= link_to "マイページへ", home_index_path, class:"btn btn-primary btn-lg"%>
      <%= link_to "掲示板一覧へ", boards_path, class:"btn btn-secondary btn-lg btn-top"%>
    </div>
    <h3 class="title-text text-center"><%= @board.title %></h2>
    <table class="data-table">
      <tbody>
        <% if @board.question != "" %>
        <tr>
          <th class="table_column1">質問内容</th>
          <td class="table_column2"><%= @board.question %></td>
        </tr>
        <% end %>

        <% if @board.impressions != "" %>
        <tr>
          <th class="table_column1">住んでみての感想</th>
          <td class="table_column2"><%= @board.impressions %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% if @board.image.attached? %>
      <%= image_tag @board.image, class:"img-fluid mx-auto d-block"%>
    <% end %>
    <div id="map"></div>


<script>
  let map;

  function initMap() {
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: gon.board.latitude,
        lng: gon.board.longitude
      },
      zoom: 17,
    });

    marker = new google.maps.Marker({
      position: {
        lat: gon.board.latitude,
        lng: gon.board.longitude
      },
      map: map
    });
  }
</script>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GMAP_API'] %>&callback=initMap">
</script>

    <table class="data-table">
      <tbody>
        <tr>
          <th class="table_column1">投稿者</th>
          <td class="table_column2"><%= @board.user.nickname %></td>
        </tr>
        <tr>
          <th class="table_column1">都道府県</th>
          <td class="table_column2"><%= @board.prefecture.name %></td>
        </tr>
        <tr>
          <th class="table_column1">市区町村</th>
          <td class="table_column2"><%= @board.municipality %></td>
        </tr>
        <% if @board.edaban != "" %>
        <tr>
          <th class="table_column1">番地</th>
          <td class="table_column2"><%= @board.edaban %></td>
        </tr>
        <% end %>

        <% if @board.building_name != "" %>
        <tr>
          <th class="table_column1">建物名・マンション名</th>
          <td class="table_column2"><%= @board.building_name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <% if @board.user_id == current_user.id %>
    <div class="show-btn-box">
      <%= link_to "掲示板を編集", edit_board_path(@board.id), class:"btn btn-primary btn-lg" %>
      <%= link_to "掲示板を削除", board_path(@board.id),method: :delete, class:"btn btn-danger btn-lg btn-top" %>
    </div>
    <% else %>
      <div id="likes_buttons_"<%= @board.id %>>
      <%= render 'likes/like', board: @board %>
      </div> 
    <% end %>
  </div>

  <div class="comment-box">
    <% if @comments != nil %>
      <% @comments.each do |comment| %>
        <% if comment.user_id != current_user.id %>
          <%= comment.user.nickname %>
          <div class="other-comment">
              <%= comment.text %>
          </div>
        <% else %>
          <div class="text-right">あなた</div>
            <div class="your-comment">
            <%= comment.text %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <%= form_with(model: [@board, @comment], local: true) do |f| %>
    <div class="text-danger">
    <%= flash[:error_messages] %>
    </div>
      <%= f.text_area :text, id:"text", class:"comment-form"%>
      <%= f.hidden_field :board_id, value: @board.id %>
      <%= f.submit "コメントを送信する", class:"btn btn-secondary btn-lg btn-block" %>
    <% end %>
  </div>
</div>

app/views/buildings/index.html.erb
<%= render partial: "layouts/nav"%>
<div class="box">
  <div class="bgImg src1 img-fluid"></div>
  <div class="bgImg src2 img-fluid"></div>
  <div class="bgImg src3 img-fluid"></div>
  <div class="bgImg src4 img-fluid"></div>
</div>
<div class="center-box text-center">
  <h5>不動産専門掲示板サイト</h5>
  <div class="center-name">Build Us</div>
  <h5>家探しで気になる点を気軽に掲示板で聞いてみましょう</h5>
</div>

app/views/home/index.html.erb
<%= render partial: "layouts/nav"%>
<div class="main-box">
  <div class="header-image">
    <%= image_tag "top-image2.jpg", class:"top-image2 img-fluid" %>
    <div class="theme text-center text-nowrap">「住みたい」を見つけましょう</div>
  </div>
  
  <div class="board-btn-box">
    <div class="home-btn-box">
    <%= link_to "掲示板を見に行く", boards_path, class:"btn btn-primary btn-lg btn-index"%>
    <%= link_to "掲示板を作成する", new_board_path, class:"btn btn-primary btn-lg btn-index"%>
    </div>

  <div class="container">
  <div class="row">
 
  
  <div class="col-lg-6">
  <h2 class="container-headline">✔︎ あなたの投稿した掲示板</h2>
  <ul class="board-box">
  <% if current_user.boards != nil %>
  <% current_user.boards.each do |board|%>
  <li class="card" style="width: 18rem;">
    <% if board.image.attached? %>
      <%= image_tag board.image, class: "bd-placeholder-img card-img-top" %>
    <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="50%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">No Image</text></svg>
    <% end %>
    <div class="card-body">
      <h4 class="card-title"><%= board.title %></h4>
      <p class="card-text"><%= board.prefecture.name %></p>
      <p class="card-text"><%= board.municipality %></p>
      <%= link_to "投稿詳細へ", board_path(board.id),method: :get, class:"btn btn-primary"%>
      <p class="card-text"><small class="text-muted">投稿日時 <%= board.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
    </div>
  </li>
  <% end %>
  <% end %>
  </ul>
  </div>
  
  <div class="col-lg-6">
    <h2 class="container-headline">✔︎ 気になる！をした掲示板</h2>
    <ul class="board-box">
      <% current_user.like_boards.each do |board| %>
      <li class="card" style="width: 18rem;">
        <% if board.image.attached? %>
      <%= image_tag board.image, class: "bd-placeholder-img card-img-top" %>
        <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="50%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">No Image</text></svg>
        <% end %>
      <div class="card-body">
      <h4 class="card-title"><%= board.title %></h4>
      <p class="card-text"><%= board.prefecture.name %></p>
      <p class="card-text"><%= board.municipality %></p>
      <%= link_to "投稿詳細へ", board_path(board.id),method: :get, class:"btn btn-primary"%>
      <p class="card-text"><small class="text-muted">投稿日時 <%= board.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
    </div>
  </li>
      <% end %>
    </ul>

  </div>
  </div>
  </div>
  </div>
  
</div>

app/views/layouts/_board_index.html.erb
<div class="main-box">
  <div class="header-box">
    <h1 class="header-text header-border">掲示板一覧</h1>
  </div>

  <div class="form-box">
    <div class="home-btn-box">
    <%= link_to "マイページへ", root_path, class:"btn btn-secondary btn-lg btn-index"%>
    </div>
    <div class="form-inline my-2 my-lg-0 d-flex justify-content-center">
    <%= form_tag(search_boards_path, :method => "get") do %>
      <%= text_field_tag :search, "",{class:"form-control mr-sm-2"} %> 
      <%= submit_tag "検索" ,:name => nil ,class: "btn btn-outline-success my-2 my-sm-0"%> 
    <% end %> 
    </div>

    <div class="card-padding">
    <% if @boards != nil %>
    <% @boards.each do |board|%>
    <div class="card mb-3 move-right">
    <% if board.image.attached? %>
      <%= image_tag board.image, class:"bd-placeholder-img card-img-top" %>
    <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">No Image</text></svg>
    <% end %>
      <div class="card-body">
        <h4 class="card-title"><%= board.title %></h4>
        <p class="card-text"><%= board.prefecture.name %></p>
        <p class="card-text"><%= board.municipality %></p>
        <%= link_to "投稿詳細へ", board_path(board.id),method: :get, class:"btn btn-primary"%>
        <p class="card-text"><small class="text-muted">投稿日時 <%= board.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
      </div>
    </div>
    <% end %>
    </div>
    <% end %>
    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='text-danger'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer"></div>

app/views/layouts/_form.html.erb
<div class="form-box">

    <%= form_with model: @board, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <label for="exampleInputEmail1">タイトル</label>
      <span class="badge badge-pill badge-danger">必須</span>
        <%= f.text_field :title, class:"form-control", id:"title" %>
    </div>
    <div class="form-group">
      <label for="exampleFormControlSelect1">都道府県</label>
      <span class="badge badge-pill badge-danger">必須</span>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name,{prompt: false}, {class:"form-control",id:"exampleFormControlSelect1"}) %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">市区町村</label>
      <span class="badge badge-pill badge-danger">必須</span>
        <%= f.text_field :municipality, class:"form-control", id:"municipality", placeholder:"〇〇市〇〇町"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">番地</label>
      <span class="badge badge-pill badge-secondary">任意</span>
        <%= f.text_field :edaban, class:"form-control", id:"edaban", placeholder:"〇丁目〇番地"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">建物名・マンション名</label>
      <span class="badge badge-pill badge-secondary">任意</span>
        <%= f.text_field :building_name, class:"form-control", id:"building_name"%>
    </div>
    <div class="form-group">
      <label for="exampleFormControlFile1">外観写真</label>
      <span class="badge badge-pill badge-secondary">任意</span>
        <%= f.file_field :image, class:"form-control-file", id:"item-image" %>
    </div>
    <span class="badge badge-pill badge-danger">いずれか必須</span>
    <div class="form-group">
      <label for="exampleInputPassword1">質問内容</label>
      <%= f.text_area :question, class:"form-control", id:"question"%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">住んでみての感想</label>
      <%= f.text_area :impressions, class:"form-control", id:"impressions"%>
    </div>
      <%= f.submit "掲示板作成",class:"btn btn-primary" %>
    </div>

    <% end %>
    
  </div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #c7c6c6;">
  <%= link_to "Build Us", root_path, class:"navbar-brand app-name" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav text-right">
      <% if user_signed_in? %>
        <li class="nav-item nav-link">
          <%= current_user.nickname%><%="さん"%>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path,method: :get, class:"nav-link"%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ゲストログイン(閲覧用)", buildings_guest_sign_in_path,method: :post, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class:"nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuildUsApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
        
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/likes/_like.html.erb
<% if current_user.already_liked?(board) %>
   <%= link_to board_like_path(@board.id), method: :delete do %>
       <button type="button" class="btn btn-outline-success">気になる！済</button>
   <% end %>
<% else %>
   <%= link_to board_likes_path(board), method: :post do %>
       <button type="button" class="btn btn-success ">気になる！</button>
   <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @board.id %>').html("<%= j(render partial: 'likes/like', locals: {board: @board}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @board.id %>').html("<%= j(render partial: 'likes/like', locals: {board: @board}) %>");